config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  get "/users", to: "users#index"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/edit-profile/:id", to: "users#edit", as: "update_profile"
  delete "/users/:id", to: "users#destroy", as: "delete_user"
  patch "/users/:id", to: "users#update"


  get "/listings/new/", to: "listings#new", as: "new_listing"
  get "/listings/index", to: "listings#index", as: "listings"
  post "/listings/new", to: "listings#create"
  get "/listings/:id", to: "listings#show", as: "show_listing"
  delete "/listings/:id", to: "listings#destroy", as: "delete_listing"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one_attached :main_image
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :listings
  
  after_create :assign_default_role
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date, :phone_number, :bio, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :birth_date, :phone_number, :bio, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  # def show
  #   @user = User.find(params[:user_id])
  #   @listing = @user.listing.create(listing_params)
  # end

  def index
    @listings = Listing.all
  end
  
  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = User.find(current_user.id).listings.build
  end

  def create
    @listing = User.find(current_user.id).listings.new(listing_params)

    if @listing.save
      redirect_to root_path
    else
      flash[:alert] = "Invalid details"
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    if current_user.id != @listing.user_id
      authorize User
    end
    @listing.destroy
    redirect_to root_path
    flash[:alert] = "User Deleted"
  end

  private
    def listing_params
      params.require(:listing).permit(:title, :body, :city, :price, :address_line_1, :address_line_2, :postcode, :main_image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    # lets users access only their own profiles
    # except admins who can access all profiles
    if current_user.id != @user.id
      authorize User
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize User
    @user.avatar.purge
    @user.destroy
    redirect_to root_path
    flash[:alert] = "User Deleted"
  end

  def edit
    @user = User.find(params[:id])
    # lets users edit only their own profiles
    # except admins who can access all profiles
    if current_user.id != @user.id
      authorize User
    end
  end
  
  def update
    @user = User.find(params[:id])
    # TODO, make avatar deletion optional
    # Included - or there would currently be no way to change avatar
    if @user.avatar.attached?
      @user.avatar.purge
    end
    if current_user.id != @user.id
      authorize User
    end
    if @user.update(user_update_params)
      redirect_to @user
    else
      flash[:alert] = "Invalid details"
    end
  end

  private
    def user_update_params
      params.require(:user).permit(:first_name, :last_name, :birth_date, :phone_number, :bio, :listing, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Hi there</h1>
<p>Welcome to Fitby, a marketplace for independently run fitness classes</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar mb-5" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%= link_to "Create Listing", new_listing_path, class: "navbar-item" %>
      <%= link_to "View Listings", listings_path, class: "navbar-item" %>
    </div>

    

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
              <%= link_to 'Manage Users', users_path, class: "button is-warning" %>
            <% end %>
            <%= link_to 'Account', user_path(current_user.id), class: "button is-light" %>
            <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "button is-light" %>
          <% else %>
            <%= link_to 'Register', new_user_registration_path, class: "button is-light" %>
            <%= link_to 'Log In', new_user_session_path, class: "button is-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="container is-max-widescreen">
    <%=render "layouts/navbar" %>
    <div class="columns is-mobile is-centered">
      <div>
        <%= yield %>
        <% flash.each do |key, msg| %>
          <div class="notification is-warning">
            <%= msg %>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/listings/index.html.erb
<table class="table">
  <tr>
    <th>Image</th>
    <th>User</th>
    <th>Title</th>
    <th>City</th>
    <th>Price</th>
    <th>View</th>
  </tr>
  <% @listings.each do |listing|%>
    <tr>
      <td>
        <% if listing.main_image.attached? %>
          <%= cl_image_tag listing.main_image.key, width: 300, cloud_name: 'dsshkpbix' %>
        <% end %>
      </td>
      <% user_name = User.find(listing.user_id).first_name + ' ' + User.find(listing.user_id).last_name %>
      <td><%= link_to user_name, user_path(listing.user.id) %></td>
      <td><%= listing.title %></td>
      <td><%= listing.city %></td>
      <td><%= listing.price %></td>
      <td>
        <%= link_to 'View Listing', show_listing_path(listing.id), class: "button is-light" %>
        <% if current_user.has_role? :admin || (current_user.id == listing.user_id)%>
          <%= button_to "Delete Listing", delete_listing_path(listing.id), class: "button is-danger", method: :delete %>
        <% end %>
      </td>
    <tr>
  <% end %>
</table>

app/views/listings/new.html.erb
<h2>New Listing</h2>

<%= form_with object: @listing, scope: :listing do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body, size:"70x5" %>
  </p>
  <p>
    <%= f.label :address_line_1 %>
    <%= f.text_field :address_line_1 %>
  </p>
  <p>
    <%= f.label :address_line_2 %>
    <%= f.text_field :address_line_2 %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :postcode %>
    <%= f.text_field :postcode %>
  </p>
  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :main_image %>
    <%= f.file_field :main_image %>
  <p>
  <%= f.submit "Create Listing" %>
  </p>
  </div>
<% end %>

app/views/listings/show.html.erb
<h1 class="title">
  <%= @listing.title %>
</h1>

<% if @listing.main_image.attached? %>
  <%= cl_image_tag @listing.main_image.key, width: 300, cloud_name: 'dsshkpbix' %>
<% end %>
<p><%= @listing.body %></p>  
<p><%= @listing.address_line_1 %></p> 
<p><%= @listing.address_line_2 %></p>
<p><%= @listing.city %></p>
<p><%= @listing.postcode %></p>
<emphasis>$<%= @listing.price %></emphasis>
<h3>Posted by:</h3>
<% user_name = User.find(@listing.user_id).first_name + ' ' + User.find(@listing.user_id).last_name %>
<p><%= link_to user_name, user_path(@listing.user.id) %></p>

app/views/users/edit.html.erb
<%= form_with model: @user do |f| %>
  <div class="field">
    <%= f.label :first_name, "First Name" %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name, "Last Name" %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :birth_date, "Date of Birth" %><br />
    <%= f.date_field :birth_date %>
  </div>

  <div class="field">
    <%= f.label :phone_number, "Phone Number" %><br />
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :bio, "Your bio" %><br />
    <%= f.text_area :bio, size:"70x5" %>
  </div>

  <div class ="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>  
<% end %>

app/views/users/index.html.erb
<table class="table">
  <tr>
    <th>User ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Role(s)</th>
    <th>Options</th>
  </tr>
  <% @users.each do |user|%>
    <tr>
      <td><%= link_to user.id, user_path(user.id) %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.roles.pluck(:name) %></td>
      <td>
        <%= button_to "Delete User", delete_user_path(user.id), class: "button is-danger", method: :delete %>
      </td>
    <tr>
  <% end %>
</table>